// Save file constants.
pub const SIGNATURE: &[u8] = b"FALLOUT SAVE FILE";
pub const PREVIEW_SIZE: usize = 29_792; // 224x133 thumbnail
pub const HEADER_PADDING: usize = 128;

pub const SAVEABLE_STAT_COUNT: usize = 35;
pub const SKILL_COUNT: usize = 18;
pub const PERK_COUNT: usize = 119;
pub const KILL_TYPE_COUNT: usize = 19;
pub const PC_STAT_COUNT: usize = 5;
pub const TAGGED_SKILL_COUNT: usize = 4;

// Object type extracted from PID: (pid >> 24) & 0x0F.
pub const OBJ_TYPE_ITEM: i32 = 0;
pub const OBJ_TYPE_CRITTER: i32 = 1;
pub const OBJ_TYPE_MISC: i32 = 5;

pub fn obj_type_from_pid(pid: i32) -> i32 {
    (pid >> 24) & 0x0F
}

// --- Display name tables ---

pub const STAT_NAMES: [&str; SAVEABLE_STAT_COUNT] = [
    "Strength",
    "Perception",
    "Endurance",
    "Charisma",
    "Intelligence",
    "Agility",
    "Luck",
    "Max HP",
    "Max AP",
    "Armor Class",
    "Unarmed Damage",
    "Melee Damage",
    "Carry Weight",
    "Sequence",
    "Healing Rate",
    "Critical Chance",
    "Better Criticals",
    "DT Normal",
    "DT Laser",
    "DT Fire",
    "DT Plasma",
    "DT Electrical",
    "DT EMP",
    "DT Explosion",
    "DR Normal",
    "DR Laser",
    "DR Fire",
    "DR Plasma",
    "DR Electrical",
    "DR EMP",
    "DR Explosion",
    "Radiation Resistance",
    "Poison Resistance",
    "Age",
    "Gender",
];

pub const SKILL_NAMES: [&str; SKILL_COUNT] = [
    "Small Guns",
    "Big Guns",
    "Energy Weapons",
    "Unarmed",
    "Melee Weapons",
    "Throwing",
    "First Aid",
    "Doctor",
    "Sneak",
    "Lockpick",
    "Steal",
    "Traps",
    "Science",
    "Repair",
    "Speech",
    "Barter",
    "Gambling",
    "Outdoorsman",
];

pub const PERK_NAMES: [&str; PERK_COUNT] = [
    "AWARENESS",
    "BONUS HTH ATTACKS",
    "BONUS HTH DAMAGE",
    "BONUS MOVE",
    "BONUS RANGED DAMAGE",
    "BONUS RATE OF FIRE",
    "EARLIER SEQUENCE",
    "FASTER HEALING",
    "MORE CRITICALS",
    "NIGHT VISION",
    "PRESENCE",
    "RAD RESISTANCE",
    "TOUGHNESS",
    "STRONG BACK",
    "SHARPSHOOTER",
    "SILENT RUNNING",
    "SURVIVALIST",
    "MASTER TRADER",
    "EDUCATED",
    "HEALER",
    "FORTUNE FINDER",
    "BETTER CRITICALS",
    "EMPATHY",
    "SLAYER",
    "SNIPER",
    "SILENT DEATH",
    "ACTION BOY",
    "MENTAL BLOCK",
    "LIFEGIVER",
    "DODGER",
    "SNAKEATER",
    "MR FIXIT",
    "MEDIC",
    "MASTER THIEF",
    "SPEAKER",
    "HEAVE HO",
    "FRIENDLY FOE",
    "PICKPOCKET",
    "GHOST",
    "CULT OF PERSONALITY",
    "SCROUNGER",
    "EXPLORER",
    "FLOWER CHILD",
    "PATHFINDER",
    "ANIMAL FRIEND",
    "SCOUT",
    "MYSTERIOUS STRANGER",
    "RANGER",
    "QUICK POCKETS",
    "SMOOTH TALKER",
    "SWIFT LEARNER",
    "TAG",
    "MUTATE",
    "NUKA COLA ADDICTION",
    "BUFFOUT ADDICTION",
    "MENTATS ADDICTION",
    "PSYCHO ADDICTION",
    "RADAWAY ADDICTION",
    "WEAPON LONG RANGE",
    "WEAPON ACCURATE",
    "WEAPON PENETRATE",
    "WEAPON KNOCKBACK",
    "POWERED ARMOR",
    "COMBAT ARMOR",
    "WEAPON SCOPE RANGE",
    "WEAPON FAST RELOAD",
    "WEAPON NIGHT SIGHT",
    "WEAPON FLAMEBOY",
    "ARMOR ADVANCED I",
    "ARMOR ADVANCED II",
    "JET ADDICTION",
    "TRAGIC ADDICTION",
    "ARMOR CHARISMA",
    "GECKO SKINNING",
    "DERMAL IMPACT ARMOR",
    "DERMAL IMPACT ASSAULT ENHANCEMENT",
    "PHOENIX ARMOR IMPLANTS",
    "PHOENIX ASSAULT ENHANCEMENT",
    "VAULT CITY INOCULATIONS",
    "ADRENALINE RUSH",
    "CAUTIOUS NATURE",
    "COMPREHENSION",
    "DEMOLITION EXPERT",
    "GAMBLER",
    "GAIN STRENGTH",
    "GAIN PERCEPTION",
    "GAIN ENDURANCE",
    "GAIN CHARISMA",
    "GAIN INTELLIGENCE",
    "GAIN AGILITY",
    "GAIN LUCK",
    "HARMLESS",
    "HERE AND NOW",
    "HTH EVADE",
    "KAMA SUTRA MASTER",
    "KARMA BEACON",
    "LIGHT STEP",
    "LIVING ANATOMY",
    "MAGNETIC PERSONALITY",
    "NEGOTIATOR",
    "PACK RAT",
    "PYROMANIAC",
    "QUICK RECOVERY",
    "SALESMAN",
    "STONEWALL",
    "THIEF",
    "WEAPON HANDLING",
    "VAULT CITY TRAINING",
    "ALCOHOL RAISED HIT POINTS",
    "ALCOHOL RAISED HIT POINTS II",
    "ALCOHOL LOWERED HIT POINTS",
    "ALCOHOL LOWERED HIT POINTS II",
    "AUTODOC RAISED HIT POINTS",
    "AUTODOC RAISED HIT POINTS II",
    "AUTODOC LOWERED HIT POINTS",
    "AUTODOC LOWERED HIT POINTS II",
    "EXPERT EXCREMENT EXPEDITOR",
    "WEAPON ENHANCED KNOCKOUT",
    "JINXED",
];

pub const KILL_TYPE_NAMES: [&str; KILL_TYPE_COUNT] = [
    "Man",
    "Woman",
    "Child",
    "Super Mutant",
    "Ghoul",
    "Brahmin",
    "Radscorpion",
    "Rat",
    "Floater",
    "Centaur",
    "Robot",
    "Dog",
    "Mantis",
    "Deathclaw",
    "Plant",
    "Gecko",
    "Alien",
    "Giant Ant",
    "Big Bad Boss",
];
